"""
airs_v2/reasoning/symbolic_validator.py
=========================================

Symbolic Validator — Deterministic Physical Rule Engine
---------------------------------------------------------

The SymbolicValidator is the core neuro-symbolic gate in Stage 3.  It receives
raw ``CausalHypothesis`` objects generated by the ``HypothesisEngine`` and
applies five physical rules derived from the Stage 2 ContextGraph topology.

**Zero tolerance**: the first rule violation immediately moves the hypothesis
to ``rejected_hypotheses``.  Subsequent rules are not checked (fail-fast).

The five rules
--------------
R1_NODE_EXISTS
    The candidate node must be registered in the ContextGraph.
    Catches hallucinated service names that never appear in our topology.

R2_BLAST_RADIUS
    The candidate must lie within the depth-2 blast radius of the focal
    service.  Enforces the Stage 2 correctness invariant: no node farther
    than 2 hops may appear in the analysis.

R3_PATH_VALID
    Every consecutive pair (a, b) in ``causal_path`` must correspond to a
    real dependency edge in the graph.  Since causal paths run root→symptom
    (opposite of dependency direction), the check is:
        ``g.has_edge(b, a)``  — "b DEPENDS_ON a, so a's failure cascades to b"

R4_DIRECTION
    The focal service must be reachable from the candidate following the
    directed dependency graph (focal → ... → candidate), meaning the
    candidate is an upstream dependency.  Self-faults (candidate == focal)
    pass trivially.

R5_HEALTH_COHERENCE (advisory, non-rejecting)
    If the candidate node is ``"healthy"`` AND metrics show
    ``connection_saturation < 0.5``, reduce ``raw_score`` by 30%.
    This is advisory-only because ``MetricsSnapshot.stale=True`` throughout
    Stage 2 — we never reject based on stale data.

TopologyContext
---------------
The validator consumes a ``TopologyContext`` dataclass that wraps the
ContextGraph, blast radius set, and optional metrics.  This object is
constructed once per incident and shared across all hypothesis validations.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import networkx as nx

from airs_v2.context.graph import ContextGraph
from airs_v2.reasoning.causal_types import (
    CausalHypothesis,
    RejectedHypothesis,
    RootCauseHypothesis,
    CausalEvidence,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Rule identifiers (machine-readable)
# ---------------------------------------------------------------------------

R1_NODE_EXISTS = "R1_NODE_EXISTS"
R2_BLAST_RADIUS = "R2_BLAST_RADIUS"
R3_PATH_VALID = "R3_PATH_VALID"
R4_DIRECTION = "R4_DIRECTION"
R5_HEALTH_COHERENCE = "R5_HEALTH_COHERENCE"  # advisory only


# ---------------------------------------------------------------------------
# Advisory scoring constants
# ---------------------------------------------------------------------------

# R5b — Transient-evidence discount
# Applied when a hypothesis's evidence is exclusively from transient-candidate
# templates AND the evidence count is below this threshold.
# Kept as a separate knob from min_recurrence (router-layer) to allow
# independent tuning of perception vs. reasoning quality gates.
TRANSIENT_MIN_EVIDENCE: int = 2
TRANSIENT_SCORE_FACTOR: float = 0.50  # 50% cut (stronger than R5a's 30%)

# R5c — Contextual-corroboration discount
# Applied to "threshold-contextual" patterns (dual-nature faults) when no
# corroborating evidence key is present on the same hypothesis.
# database_query_timeout alone (with no pool/thread exhaustion evidence) is
# insufficient for a high-confidence incident escalation.
CONTEXTUAL_SCORE_FACTOR: float = 0.60  # 40% cut
CONTEXTUAL_TEMPLATE_KEYS: frozenset[str] = frozenset({"database_query_timeout"})
# Evidence keys that corroborate a contextual template signal
CONTEXTUAL_CORROBORATION_KEYS: frozenset[str] = frozenset({
    "connection_pool_exhausted",
    "thread_pool_exhausted",
    "transaction_leak",
})


# ---------------------------------------------------------------------------
# Topology context
# ---------------------------------------------------------------------------


@dataclass
class TopologyContext:
    """
    Lightweight topology snapshot shared across all validations in one incident.

    Attributes
    ----------
    graph:
        The ContextGraph instance (Stage 2).
    focal_service:
        The focal service for the incident.
    blast_radius_nodes:
        Set of node names within depth-2 of focal_service (from
        ``BlastRadiusResult.affected_services``).  Does NOT include focal itself
        — the validator adds it so self-faults are always in scope.
    metrics_by_node:
        Optional dict mapping node name → saturation float (from
        ``MetricsSnapshot.connection_saturation``).  Used only by R5.
    health_by_node:
        Optional dict mapping node name → health_status string.  Used by R5.
    on_call_by_node:
        Optional dict mapping node name → list[str] on-call contacts.
    """

    graph: ContextGraph
    focal_service: str
    blast_radius_nodes: set[str] = field(default_factory=set)
    metrics_by_node: dict[str, float] = field(default_factory=dict)
    health_by_node: dict[str, str] = field(default_factory=dict)
    on_call_by_node: dict[str, list[str]] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Always include focal service in the blast radius scope
        self.blast_radius_nodes.add(self.focal_service)

    # ------------------------------------------------------------------
    # Topology helpers
    # ------------------------------------------------------------------

    def has_node(self, name: str) -> bool:
        return self.graph._g.has_node(name)

    def has_dep_edge(self, dependent: str, dependency: str) -> bool:
        """Return True if 'dependent' DEPENDS_ON 'dependency' in the graph."""
        return self.graph._g.has_edge(dependent, dependency)

    def reachable(self, source: str, target: str) -> bool:
        """
        Return True if 'target' is reachable from 'source' following
        directed dependency edges (source depends on ... depends on target).
        """
        if source == target:
            return True
        try:
            return nx.has_path(self.graph._g, source, target)
        except nx.NodeNotFound:
            return False


# ---------------------------------------------------------------------------
# Symbolic Validator
# ---------------------------------------------------------------------------


class SymbolicValidator:
    """
    Deterministic five-rule physical constraint checker.

    Usage
    -----
    ::

        ctx = TopologyContext(graph=g, focal_service="payments-service",
                              blast_radius_nodes={"payments-db", ...})
        validator = SymbolicValidator(ctx)
        valid, rejected = validator.validate_all(raw_hypotheses)
    """

    def __init__(self, context: TopologyContext) -> None:
        self._ctx = context

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate_all(
        self,
        hypotheses: list[CausalHypothesis],
    ) -> tuple[list[CausalHypothesis], list[RejectedHypothesis]]:
        """
        Validate all hypotheses, splitting them into valid and rejected sets.

        Returns
        -------
        valid:   List of hypotheses that passed all 5 rules (R5 may have
                 modified their ``raw_score``).
        rejected: List of ``RejectedHypothesis`` with machine-readable rule ID
                  and human-readable reason.
        """
        valid: list[CausalHypothesis] = []
        rejected: list[RejectedHypothesis] = []

        for h in hypotheses:
            result = self._validate_one(h)
            if isinstance(result, RejectedHypothesis):
                rejected.append(result)
                logger.debug(
                    "[SymbolicValidator] REJECT candidate=%s rule=%s reason=%s",
                    h.candidate_node,
                    result.violated_rule,
                    result.reason,
                )
            else:
                # result is the (possibly score-modified) hypothesis
                valid.append(result)
                logger.debug(
                    "[SymbolicValidator] ACCEPT candidate=%s score=%.3f",
                    h.candidate_node,
                    h.raw_score,
                )

        logger.info(
            "[SymbolicValidator] focal=%s valid=%d rejected=%d total=%d",
            self._ctx.focal_service,
            len(valid),
            len(rejected),
            len(hypotheses),
        )
        return valid, rejected

    def build_root_cause(
        self,
        h: CausalHypothesis,
        rank: int,
    ) -> RootCauseHypothesis:
        """
        Promote a validated ``CausalHypothesis`` to a ``RootCauseHypothesis``.

        Resolves on-call contacts from the topology context and determines
        the propagation mechanism from the causal path length.
        """
        contacts = self._ctx.on_call_by_node.get(h.candidate_node, [])

        # Determine propagation mechanism
        path_len = len(h.causal_path)
        if path_len <= 2:
            mechanism = "depends_on"
        elif path_len == 3:
            mechanism = "cascade"
        else:
            mechanism = "correlation"

        return RootCauseHypothesis(
            candidate_node=h.candidate_node,
            template_key=h.template_key,
            rank=rank,
            final_score=min(h.raw_score, 1.0),
            evidence=h.evidence,
            causal_path=h.causal_path,
            propagation_mechanism=mechanism,
            on_call_contacts=contacts,
            stale_metrics_warning=True,  # invariant: Stage 2 metrics are always stale
        )

    # ------------------------------------------------------------------
    # Internal — rule checks (fail-fast)
    # ------------------------------------------------------------------

    def _validate_one(
        self, h: CausalHypothesis
    ) -> CausalHypothesis | RejectedHypothesis:
        """Apply rules R1–R5 in order.  Returns the hypothesis on pass or a rejection."""

        # R1 — Node existence
        if not self._ctx.has_node(h.candidate_node):
            return RejectedHypothesis(
                hypothesis=h,
                violated_rule=R1_NODE_EXISTS,
                reason=(
                    f"Node '{h.candidate_node}' does not exist in the topology "
                    f"(known nodes: {sorted(self._ctx.graph.node_names())[:8]}…)"
                ),
            )

        # R2 — Blast radius containment
        if h.candidate_node not in self._ctx.blast_radius_nodes:
            return RejectedHypothesis(
                hypothesis=h,
                violated_rule=R2_BLAST_RADIUS,
                reason=(
                    f"Node '{h.candidate_node}' is outside the depth-2 blast radius "
                    f"of '{self._ctx.focal_service}'. "
                    f"Blast radius = {sorted(self._ctx.blast_radius_nodes)}"
                ),
            )

        # R3 — Causal path validity
        path = h.causal_path
        if len(path) >= 2:
            for i in range(len(path) - 1):
                a, b = path[i], path[i + 1]
                # a causes b to fail → b DEPENDS_ON a → has_dep_edge(b, a)
                if not self._ctx.has_dep_edge(b, a):
                    return RejectedHypothesis(
                        hypothesis=h,
                        violated_rule=R3_PATH_VALID,
                        reason=(
                            f"No dependency edge between '{b}' and '{a}' in topology. "
                            f"Causal path {path} step ({a}→{b}) is physically impossible."
                        ),
                    )

        # R4 — Directional consistency
        if h.candidate_node != self._ctx.focal_service:
            if not self._ctx.reachable(self._ctx.focal_service, h.candidate_node):
                return RejectedHypothesis(
                    hypothesis=h,
                    violated_rule=R4_DIRECTION,
                    reason=(
                        f"'{h.candidate_node}' has no upstream path to "
                        f"'{self._ctx.focal_service}'. "
                        f"The focal service does not depend on this node, "
                        f"so it cannot be the root cause."
                    ),
                )

        # R5 — Health coherence (advisory, score modifier only)
        health = self._ctx.health_by_node.get(h.candidate_node, "unknown")
        saturation = self._ctx.metrics_by_node.get(h.candidate_node, 1.0)
        if health == "healthy" and saturation < 0.5:
            original = h.raw_score
            h = h.model_copy(update={"raw_score": h.raw_score * 0.70})
            logger.debug(
                "[SymbolicValidator] R5 advisory: %s health=healthy sat=%.2f "
                "score %.3f→%.3f",
                h.candidate_node,
                saturation,
                original,
                h.raw_score,
            )

        # R5b — Transient-evidence advisory (non-rejecting)
        # If ALL evidence pieces are flagged is_transient AND the count is below
        # TRANSIENT_MIN_EVIDENCE, apply a 50% score reduction.  This handles the
        # case where transient-candidate results somehow reached hypothesis
        # generation (e.g., via L2/L3 match on a transient template, or if
        # min_recurrence was lowered for a specific deployment).
        if h.evidence:
            all_transient = all(e.is_transient for e in h.evidence)
            low_count = len(h.evidence) < TRANSIENT_MIN_EVIDENCE
            if all_transient and low_count:
                original = h.raw_score
                h = h.model_copy(update={"raw_score": h.raw_score * TRANSIENT_SCORE_FACTOR})
                logger.debug(
                    "[SymbolicValidator] R5b_TRANSIENT_EVIDENCE advisory: %s "
                    "all_transient=True evidence_count=%d score %.3f→%.3f",
                    h.candidate_node,
                    len(h.evidence),
                    original,
                    h.raw_score,
                )

        # R5c — Contextual-corroboration advisory (non-rejecting)
        # database_query_timeout (and other threshold-contextual templates) are
        # dual-nature faults.  A hypothesis driven solely by this template, with
        # no corroborating evidence from pool/thread exhaustion patterns, gets a
        # 40% score discount so it stays below the incident escalation threshold
        # unless stronger corroboration is present.
        if h.evidence:
            evidence_keys = {e.template_key for e in h.evidence}
            is_contextual_only = (
                evidence_keys <= CONTEXTUAL_TEMPLATE_KEYS  # all evidence keys are contextual
                and not evidence_keys.isdisjoint(CONTEXTUAL_TEMPLATE_KEYS)  # at least one present
            )
            has_corroboration = bool(evidence_keys & CONTEXTUAL_CORROBORATION_KEYS)
            if is_contextual_only and not has_corroboration:
                original = h.raw_score
                h = h.model_copy(update={"raw_score": h.raw_score * CONTEXTUAL_SCORE_FACTOR})
                logger.debug(
                    "[SymbolicValidator] R5c_CONTEXTUAL_CORROBORATION advisory: %s "
                    "template=%s evidence_keys=%s score %.3f→%.3f",
                    h.candidate_node,
                    h.template_key,
                    sorted(evidence_keys),
                    original,
                    h.raw_score,
                )

        return h
