"""
agent/action/policy_engine.py

Policy-as-Code invariant checker for the AIRS Action Layer.

Before any automated remediation is executed, this engine evaluates the
proposed infrastructure change against a set of inviolable invariants.
The evaluation includes:

  1. Declarative JSON invariant checks (fast, in-process)
  2. Terraform HCL dry-run simulation for IaC changes (subprocess)

If ANY critical invariant is violated, execution is deterministically blocked,
regardless of the risk score or operator approval. This prevents the AIRS
from inadvertently creating a secondary outage.

Architecture:
  - invariants.json defines the rule set (declarative, version-controlled)
  - PolicyEngine.check() runs a dry-run simulation of the proposed patch
  - Terraform HCL patches are generated by generate_terraform_patch() and
    validated via `terraform validate` + custom rule checks
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Infrastructure Invariants
# ---------------------------------------------------------------------------
# Each invariant is a dict with:
#   id          — Unique identifier for audit trails
#   description — Human-readable rule description
#   severity    — "critical" (blocks execution) or "warning" (logs only)
#   check       — Callable(current_state, proposed_patch, incident_ctx) -> bool

INFRASTRUCTURE_INVARIANTS: list[dict[str, Any]] = [
    {
        "id": "MIN_REPLICAS",
        "description": "Production services must maintain at least 2 replicas",
        "severity": "critical",
        "check": lambda state, patch, ctx: (
            patch.get("replicas", state.get("replicas", 2)) >= 2
        ),
    },
    {
        "id": "NO_PUBLIC_DB_EXPOSURE",
        "description": "Database services must never be publicly accessible",
        "severity": "critical",
        "check": lambda state, patch, ctx: (
            not patch.get("public_access", state.get("public_access", False))
        ),
    },
    {
        "id": "CHANGE_WINDOW",
        "description": "Non-emergency (P2/P3) changes only during maintenance windows (00:00-06:00 UTC)",
        "severity": "warning",
        "check": lambda state, patch, ctx: (
            ctx.get("severity", "P2") in ("P0", "P1") or
            0 <= datetime.now(timezone.utc).hour < 6
        ),
    },
    {
        "id": "MAX_SCALE_FACTOR",
        "description": "Cannot scale to more than 3x current replica count in a single action",
        "severity": "critical",
        "check": lambda state, patch, ctx: (
            patch.get("replicas", state.get("replicas", 1)) <=
            max(1, state.get("replicas", 1)) * 3
        ),
    },
    {
        "id": "MIN_CONNECTION_POOL",
        "description": "Database connection pool cannot be reduced below 10 connections",
        "severity": "critical",
        "check": lambda state, patch, ctx: (
            patch.get("max_connections", state.get("max_connections", 100)) >= 10
        ),
    },
    {
        "id": "NO_NAMESPACE_DELETION",
        "description": "Namespace deletion is never permitted via automated remediation",
        "severity": "critical",
        "check": lambda state, patch, ctx: (
            "delete_namespace" not in json.dumps(patch).lower()
        ),
    },
    {
        "id": "ROLLBACK_REQUIRED",
        "description": "Every automated remediation must include a valid rollback command",
        "severity": "critical",
        "check": lambda state, patch, ctx: bool(ctx.get("rollback_command", "").strip()),
    },
]


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class InvariantViolation:
    """A single invariant that was violated by the proposed patch."""
    invariant_id: str
    description: str
    severity: str  # "critical" or "warning"


@dataclass
class PolicyCheckResult:
    """Aggregated result of an invariant check run."""
    passed: bool
    violations: list[InvariantViolation] = field(default_factory=list)
    warnings: list[InvariantViolation] = field(default_factory=list)
    simulated_state: dict[str, Any] = field(default_factory=dict)
    terraform_valid: bool = True
    terraform_errors: list[str] = field(default_factory=list)
    checked_at: datetime = field(default_factory=datetime.utcnow)

    @property
    def critical_violations(self) -> list[InvariantViolation]:
        return [v for v in self.violations if v.severity == "critical"]

    def to_markdown(self) -> str:
        if self.passed:
            return (
                "**✅ Policy Check: PASSED**\n"
                f"- All {len(INFRASTRUCTURE_INVARIANTS)} invariants satisfied.\n"
                f"- Terraform dry-run: {'✅ valid' if self.terraform_valid else '❌ invalid'}"
            )
        lines = [
            "**🚫 Policy Check: FAILED — Execution Blocked**\n",
            "### Critical Violations",
        ]
        for v in self.critical_violations:
            lines.append(f"- `[{v.invariant_id}]` {v.description}")
        if self.warnings:
            lines.append("\n### Warnings (non-blocking)")
            for w in self.warnings:
                lines.append(f"- `[{w.invariant_id}]` {w.description}")
        if self.terraform_errors:
            lines.append("\n### Terraform Errors")
            for err in self.terraform_errors:
                lines.append(f"- {err}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Terraform HCL patch generator
# ---------------------------------------------------------------------------


def generate_terraform_patch(
    service: str,
    namespace: str,
    action_type: str,
    patch_params: dict[str, Any],
) -> str:
    """
    Generate a minimal, targeted Terraform HCL patch for the proposed change.

    The generated HCL is intentionally minimal — it only modifies the
    specific resource attribute affected by the remediation action.

    Args:
        service: Target service name.
        namespace: Kubernetes namespace.
        action_type: Type of action (e.g., "scale_deployment", "restart_deployment").
        patch_params: Parameters for the action (e.g., {"replicas": 3}).

    Returns:
        HCL string representing the proposed infrastructure change.
    """
    resource_name = service.replace("-", "_")

    if action_type == "scale_deployment":
        replicas = patch_params.get("replicas", 2)
        return f"""
# AIRS Auto-Generated Terraform Patch
# Action: Scale deployment for incident remediation
# Generated at: {datetime.utcnow().isoformat()}Z

resource "kubernetes_deployment" "{resource_name}" {{
  metadata {{
    name      = "{service}"
    namespace = "{namespace}"
  }}
  spec {{
    replicas = {replicas}
  }}
}}
"""

    if action_type == "restart_deployment":
        return f"""
# AIRS Auto-Generated Terraform Patch
# Action: Trigger rolling restart via annotation patch
# Generated at: {datetime.utcnow().isoformat()}Z

resource "kubernetes_deployment" "{resource_name}" {{
  metadata {{
    name      = "{service}"
    namespace = "{namespace}"
  }}
  spec {{
    template {{
      metadata {{
        annotations = {{
          "kubectl.kubernetes.io/restartedAt" = "{datetime.utcnow().isoformat()}Z"
        }}
      }}
    }}
  }}
}}
"""

    if action_type == "update_resource_limits":
        memory = patch_params.get("memory_limit", "2Gi")
        cpu = patch_params.get("cpu_limit", "1000m")
        return f"""
# AIRS Auto-Generated Terraform Patch
# Action: Update resource limits for OOM remediation
# Generated at: {datetime.utcnow().isoformat()}Z

resource "kubernetes_deployment" "{resource_name}" {{
  metadata {{
    name      = "{service}"
    namespace = "{namespace}"
  }}
  spec {{
    template {{
      spec {{
        container {{
          name = "{service}"
          resources {{
            limits = {{
              memory = "{memory}"
              cpu    = "{cpu}"
            }}
          }}
        }}
      }}
    }}
  }}
}}
"""

    # Generic patch for unknown action types
    return f"""
# AIRS Auto-Generated Terraform Patch
# Action: {action_type}
# Generated at: {datetime.utcnow().isoformat()}Z
# NOTE: Manual review required for this action type.

# Parameters: {json.dumps(patch_params, indent=2)}
"""


def validate_terraform_hcl(hcl_content: str) -> tuple[bool, list[str]]:
    """
    Validate a Terraform HCL string by writing it to a temp directory
    and running `terraform validate`.

    Falls back gracefully (returns True with empty errors) if Terraform
    is not installed, since this is an optional production enhancement.

    Args:
        hcl_content: The HCL content to validate.

    Returns:
        Tuple of (is_valid: bool, error_messages: list[str]).
    """
    try:
        # Check if terraform is available
        result = subprocess.run(
            ["terraform", "version"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode != 0:
            raise FileNotFoundError("terraform not in PATH")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        logger.info("[PolicyEngine] Terraform not available — skipping HCL validation.")
        return True, []

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            hcl_path = Path(tmpdir) / "main.tf"
            hcl_path.write_text(hcl_content)
            result = subprocess.run(
                ["terraform", "validate", "-json"],
                capture_output=True, text=True, timeout=30, cwd=tmpdir,
            )
            if result.returncode == 0:
                return True, []
            # Parse JSON output for specific errors
            try:
                data = json.loads(result.stdout)
                errors = [
                    diag.get("summary", "Unknown error")
                    for diag in data.get("diagnostics", [])
                    if diag.get("severity") == "error"
                ]
            except json.JSONDecodeError:
                errors = [result.stderr[:200]]
            return False, errors
    except Exception as exc:
        logger.warning("[PolicyEngine] Terraform validation error: %s", exc)
        return True, []  # Don't block on validator failure


# ---------------------------------------------------------------------------
# PolicyEngine
# ---------------------------------------------------------------------------


class PolicyEngine:
    """
    Policy-as-Code invariant checker.

    Evaluates a proposed remediation patch against all infrastructure
    invariants in a simulated dry-run. Critical invariant violations
    deterministically block execution.

    Usage:
        engine = PolicyEngine()
        result = engine.check(
            proposed_patch={"replicas": 3},
            current_state={"replicas": 2, "public_access": False},
            incident_context={"severity": "P0", "rollback_command": "kubectl rollout undo ..."},
        )
        if not result.passed:
            # Route to reject_node
    """

    def check(
        self,
        proposed_patch: dict[str, Any],
        current_state: dict[str, Any],
        incident_context: dict[str, Any],
        terraform_hcl: Optional[str] = None,
    ) -> PolicyCheckResult:
        """
        Evaluate the proposed patch against all infrastructure invariants.

        Args:
            proposed_patch: The proposed state changes (e.g., {"replicas": 3}).
            current_state: The current infrastructure state.
            incident_context: Incident metadata (severity, rollback_command, etc.).
            terraform_hcl: Optional HCL content to validate via `terraform validate`.

        Returns:
            PolicyCheckResult with pass/fail status and violation details.
        """
        violations: list[InvariantViolation] = []
        warnings: list[InvariantViolation] = []

        for invariant in INFRASTRUCTURE_INVARIANTS:
            try:
                passed = invariant["check"](current_state, proposed_patch, incident_context)
            except Exception as exc:
                logger.warning("[PolicyEngine] Invariant %s check error: %s", invariant["id"], exc)
                passed = True  # Don't block on buggy invariant code

            if not passed:
                violation = InvariantViolation(
                    invariant_id=invariant["id"],
                    description=invariant["description"],
                    severity=invariant["severity"],
                )
                if invariant["severity"] == "critical":
                    violations.append(violation)
                    logger.warning(
                        "[PolicyEngine] CRITICAL invariant violated: %s \u2014 %s",
                        invariant["id"], invariant["description"],
                    )
                else:
                    warnings.append(violation)
                    logger.info(
                        "[PolicyEngine] WARNING invariant: %s \u2014 %s",
                        invariant["id"], invariant["description"],
                    )

        # Terraform HCL validation (optional)
        tf_valid = True
        tf_errors: list[str] = []
        if terraform_hcl:
            tf_valid, tf_errors = validate_terraform_hcl(terraform_hcl)
            if not tf_valid:
                logger.warning("[PolicyEngine] Terraform validation failed: %s", tf_errors)

        # Compute simulated resulting state
        simulated = {**current_state, **proposed_patch}

        # Overall pass: no critical violations AND terraform valid
        passed = len(violations) == 0 and tf_valid

        result = PolicyCheckResult(
            passed=passed,
            violations=violations,
            warnings=warnings,
            simulated_state=simulated,
            terraform_valid=tf_valid,
            terraform_errors=tf_errors,
        )

        logger.info(
            "[PolicyEngine] Check result: passed=%s violations=%d warnings=%d",
            passed, len(violations), len(warnings),
        )
        return result

    def check_from_remediation_plan(
        self,
        plan: Any,  # RemediationPlan
        service: str,
        namespace: str,
        current_state: Optional[dict] = None,
    ) -> PolicyCheckResult:
        """
        Convenience method: extract patch parameters from a RemediationPlan
        and run the full policy check including Terraform HCL generation.

        Infers action_type from the plan's step commands:
          - "rollout restart" -> restart_deployment
          - "scale" -> scale_deployment
          - "set resources" -> update_resource_limits
        """
        if current_state is None:
            current_state = {"replicas": 2, "public_access": False, "max_connections": 100}

        # Infer action type from first step command
        action_type = "generic_action"
        patch_params: dict[str, Any] = {}
        for step in getattr(plan, "steps", []):
            cmd = step.command or ""
            if "rollout restart" in cmd:
                action_type = "restart_deployment"
                break
            elif "scale" in cmd:
                action_type = "scale_deployment"
                # Try to extract replica count
                import re
                m = re.search(r"--replicas=(\d+)", cmd)
                if m:
                    patch_params["replicas"] = int(m.group(1))
                break
            elif "set resources" in cmd or "limits=memory" in cmd:
                action_type = "update_resource_limits"
                break

        incident_context = {
            "severity": "P1",
            "rollback_command": getattr(plan, "rollback_command", ""),
        }

        hcl = generate_terraform_patch(service, namespace, action_type, patch_params)

        return self.check(
            proposed_patch=patch_params,
            current_state=current_state,
            incident_context=incident_context,
            terraform_hcl=hcl,
        )
